### ISSUE TITLE
Prices aren't updating

### ISSUE THREAD

**Issue by ghost** [micro-machine/monero-monitor#2]
Hasn't worked for the past week, I think

**Comment by bigreddmachine** [comment]
Yep. I noticed that myself yesterday. Nice to hear it's not just me, not nice to hear it's an issue :-/

Looks like it is an issue with the Coin Desk API for getting the price of BTC in various currencies. I will try to get a fix asap, but it might be a few days due to other commitments. Thanks for the bug report!

Also, can you confirm that the Markets tab is still working?

**Comment by ghost** [comment]
Indeed it is :)

**Comment by bigreddmachine** [comment]
This should be fixed with 9f5bc485368b678a53333c5eb9b3335aa1af222c and the fix should be reflected in v.1.1.2 from the Chrome Store or here under "Releases". The update has been published the the Chrome Store, so installations from there should auto-update in the next few hours to day (+/-). If you want to get the update sooner, I think you can uninstall/reinstall the extension from the Chrome Store to force the update right away, but any settings you've configured will be lost.

Let me know if after a few days things still do not look correct. And thanks!
